### PR TITLE
Creating experiment tutorial

### PR DESCRIPTION
**Pull request by cguardia**
A detailed tutorial that uses the dallinger-cookiecutter template to create an experiment.

## Description
The tutorial shows how to use the cookiecutter template, and then goes file by file explaining what was created and how to extend it.

## Motivation and Context
This was requested on story 359 from ScrumDo.

### CODE REVIEW

**Comment by witekdev** [comment]
Some comments:

**1.**
Since this has been placed under the Developer documenation. Perhaps 'installation instructions` link should point to both the developer instalation instructions? or point to both. Or perhaps the target audience for this is a 'user' of Dallinger?

**2**
The test experiment does not terminate in the console, it remains here:
```
❯❯ Launching the experiment...

❯❯ Initial recruitment list:
http://0.0.0.0:5000/ad?recruiter=hotair&assignmentId=X66LLW&hitId=MQ34YZ&workerId=NNEEA3&mode=debug
Additional details:
Recruitment requests will open browser windows automatically.

❯❯ new recruitment request!
```
Not sure if this is normal but I thought I would mention it here.

**3**
Perhaps it might not be clear to people what the `top directory` of a project is.
``` To run the tests as they are, and once you start adding your own, use the pytest command. Make sure you install dev-requirements.txt before running the tests, then enter this command from the top directory of your project: ```
However they do have the example below that text, so maybe this is not important to change.

**Comment by vlall** [comment]
I like what you have so far @cguardia. I'm not sure if we should make this a separate story but part of what we also wanted was a walkthrough of a specific example experiment (like bartlett or something). Will discuss tomorrow.

**Comment by cguardia** [comment]
I think I could add a new section for this at the end of the current tutorial. Now that the reader knows everything about the basic structure/files of an experiment, we can go in detail over Bartlett's config.txt, experiment.py, models.py, experiment.js and exp.html files. This section will focus on what to change and cover the subjects that you mention above.

**Comment by vlall** [comment]
That sounds good.

**Comment by cguardia** [comment]
I updated the PR with the new extended version of the tutorial.

**Comment by cguardia** [comment]
@vlall I rebased this and fixed conflicts, but now the build is failing. Not sure what this is about, as my changes are only to the docs. Will try again tomorrow.

**Comment by cguardia** [comment]
@vlall I rebased again and this finally passes all checks.

**Pull request merged**
