### PR TITLE
Merge Development

### PR DESCRIPTION
**Pull request by vlall**
## Description
Review, test, and merge development into master.

### CODE REVIEW

**Comment by alecpm** [comment]
Rebased onto master to resolve possible merge conflicts.

**Comment by jessesnyder** [comment]
@alecpm wrote 
> We may want to consider adding a backwards compatible __call__() method to the base Recruiter implementation that just returns self so that we don't break existing experiments that call exp.recruiter().
I'm a +1 on that.

**Comment by vlall** [comment]
Cool, I tested it out too and things looked good.

**Comment by vlall** [comment]
I've run into some errors attempting to run in `sandbox` mode which I've outlined in #general.

**Comment by jessesnyder** [comment]
> SAWarning: Reassigning polymorphic association for identity 'event' from <Mapper at 0x113ea86d0; Event> to <Mapper at 0x113ec57d0; Event>: Check for duplicate use of 'event' as value for polymorphic_identity.
>   self, self.polymorphic_identity)

@vlall My understanding is that this warning will always be emitted when running GU because of the fact that it subclasses a model from Dallinger, and the manner in which we load custom experiment modules in Dallinger:
```exp = imp.load_source('dallinger_experiment', "dallinger_experiment.py")```

In Python, when you do a traditional import, the symbol table is checked to see if the module/class/etc. name has already been imported, and if so, the import is skipped. However, when you call `imp.load_source()` this check is bypassed, and the import is forced to run again. Down the chain, SQAlchemy is worried that some *different* model class has already been imported with a the same polymorphic_identity value it's currently seeing, but in fact it was the *same* class during an earlier import.

Other than the warning, there are no ill effects from this.

Tagging @alecpm and @MatthewWilkes for a confirm/deny since they're also assigned review here.

**Comment by jessesnyder** [comment]
Seeing this exception and unable to move while playing GU with a single player in the sandbox:
```
Nov 22 15:42:17 dlgr-d09fb46d app/web.1: 2017-11-22 23:42:17,384 We received a message for our channel: griduniverse_ctrl:{"type":"move","player_id":"1","move":"down"} 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1: Traceback (most recent call last): 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     result = self._run(*self.args, **self.kwargs) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/src/dallinger/dallinger/experiment_server/sockets.py", line 66, in send 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     client.send(data.decode('utf-8')) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "dallinger_experiment.py", line 1113, in send 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     self.record_event(message, message['player_id']) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "dallinger_experiment.py", line 1129, in record_event 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     info = Event(origin=node, details=details) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "<string>", line 4, in __init__ 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     manager.dispatch.init_failure(self, args, kwargs) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__ 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     compat.reraise(exc_type, exc_value, exc_tb) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     return manager.original_init(*mixed[1:], **kwargs) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/models.py", line 15, in __init__ 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     super(Event, self).__init__(origin) 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "<string>", line 6, in __init__ 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:   File "/app/.heroku/src/dallinger/dallinger/models.py", line 1453, in __init__ 
Nov 22 15:42:17 dlgr-d09fb46d app/web.1:     if origin.failed: 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__ 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:     return self.impl.get(instance_state(instance), dict_) 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:     value = state._load_expired(state, passive) 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:     self.manager.deferred_scalar_loader(self, toload) 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 659, in load_scalar_attributes 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1:     (state_str(state))) 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1: DetachedInstanceError: Instance <Node at 0x7f8b2f474850> is not bound to a Session; attribute refresh operation cannot proceed 
Nov 22 15:42:18 dlgr-d09fb46d app/web.1: Wed Nov 22 23:42:17 2017 <Greenlet at 0x7f8b2f862910: <bound method ChatBackend.send of <dallinger.experiment_server.sockets.ChatBackend object at 0x7f8b30dc8750>>(<dallinger_experiment.Griduniverse object at 0x7f8, 'griduniverse_ctrl:{"type":"move","player_id":"1",)> failed with DetachedInstanceError 
```

**Pull request merged**
