### PR TITLE
Issue CASCADE when dropping tables

### PR DESCRIPTION
**Pull request by pmcharrison**
By default sqlalchemy does not issue a CASCADE to PostgreSQL when dropping tables. This made `init_db` fail when tables depend on one another. The following MR fixes this by instructing the compiler to always issue CASCADE when dropping tables. I have tested this manually on my machine.

### CODE REVIEW

**Comment by jessesnyder** [comment]
Hi @pmcharrison Are you sure we want a postgresql-targeted solution? Would it be possible to use cascading delete syntax built into `relationship` ORM properties instead?

https://docs.sqlalchemy.org/en/14/orm/cascades.html#using-foreign-key-on-delete-cascade-with-orm-relationships

**Comment by pmcharrison** [comment]
Doesn't the relationship cascade option apply to deleting individual rows rather than dropping entire tables? When I searched around online it seemed that you needed to go this way for tables.

**Comment by jessesnyder** [comment]
Ah, I see. That makes sense.

**Review by jessesnyder — APPROVED** [review]
Question addressed. Looks like a good solution, and thanks for the code comment.

**Pull request merged**
