### PR TITLE
Enable flake8 checks and fix errors

### PR DESCRIPTION
**Pull request by davisagli**
## Description
This fixes Python code formatting that doesn't conform to PEP8, and adds a job to tox and travis to fail if new formatting errors are committed.

I think the only noteworthy change here is comparing to `sqlalchemy.sql.expression.false` in query expressions instead of using `== False` which is disallowed by PEP8. It's a workaround that I found at http://stackoverflow.com/a/18998106

## Motivation and Context
Enforcing PEP8 helps with readability of the codebase, which is important for a project involving multiple developers, and it's generally seen as a best practice for Python projects.

## How Has This Been Tested?
Tested by running flake8

### CODE REVIEW

**Comment by alecpm** [comment]
When I run tox with this branch it appears to run flake8 over my entire virtualenv, resulting in a ton of errors in other packages (including psiturk-dallinger). Perhaps it should be configured to run only over the dallinger package and the demos? Or maybe my config is borked?

**Comment by davisagli** [comment]
@alecpm oh, my virtualenv is outside the git repository so that's why I didn't notice that. Better now?

**Comment by davisagli** [comment]
Rebased on master and renamed the tox environment to `style`

**Comment by alecpm** [comment]
It's still not working for me (src/psiturk-dallinger and various stuff in bin is causing failures), but I should probably just move my virtualenv up a level to be consistent with everyone else's config.

**Comment by davisagli** [comment]
Makes sense to me to also exclude `bin` and `src`, which I just did.

**Comment by davisagli** [comment]
I'm going to have to get used to the 50-char limit on the first line of the commit message.

**Comment by alecpm** [comment]
That did the trick, looks all good from here.

**Pull request merged**
