### PR TITLE
Introduce config variable 'lock_table_when_creating_participant'

### PR DESCRIPTION
**Pull request by pmcharrison**
The `create_participant` route ordinarily begins by locking the Participant table (see `experiment_server.py`):

```py
try:
    session.connection().execute(
        "LOCK TABLE participant IN EXCLUSIVE MODE NOWAIT"
    )
except exc.OperationalError as e:
    e.orig = TransactionRollbackError()
    raise e
```

If this command happens to run at the same time as another server process that interacts with the participant table, it is possible for a deadlock to occur. In such cases the entire server process freezes. This could lead to timeouts in participant requests.

Another approach would be to rewrite experiment code to avoid such deadlocks. In theory one should be able to introduce other locks on the experiment side to avoid such deadlocks occurring. However it is hard to get this right in SQLAlchemy and we have not yet managed to fix the problem that way.

This PR introduces a config variable 'lock_table_when_creating_participant' that defaults to True, preserving the previous behaviour, but can be optionally set to False, in which case Dallinger will no longer lock the database table. This seems to fix the problems that we have been experiencing but we would like to keep an eye on this to see what the long-term implications are.

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
I think you're right @alecpm, I believe this was part of debugging intermittent failures when a large number of users joined at once from mturk. If I recall correctly, we were getting situations where users at the recruitment limit were joining in parallel, causing the experiment to fail to start. It was a long time ago, though.

**Review by jessesnyder — APPROVED** [review]
I'm also OK with merging this as a means to verify that it fixes the deadlock problem, but I feel like there's an underlying problem we might be able to solve that would make it (or even better, the table lock) unnecessary, and we should dig into this at some point.

**Comment by MatthewWilkes** [comment]
I think you're right @alecpm, I believe this was part of debugging intermittent failures when a large number of users joined at once from mturk. If I recall correctly, we were getting situations where users at the recruitment limit were joining in parallel, causing the experiment to fail to start. It was a long time ago, though.

**Comment by MatthewWilkes** [comment]
So, I've been thinking a bit more about this over the course of the evening. I believe we also tried changing the isolation level to SERIALIZABLE, but that wasn't sufficient. That's probably a sign that something was wrong with the locking, just by itself.

In terms of preventing deadlocks, they'd happen when the locking of one thread is an inverse of another. That is, if thread 1 acquires locks A then B, but 2 acquires B then A. I think I thought this was safe because other tables weren't locked, but I am not sure that is true. One thing to try might be to explicitly lock the participants table early in the other request, before other locks happen. That'd really be fighting fire with fire though, I think removing or reducing locking is much more preferable.

**Comment by alecpm** [comment]
Thanks @MatthewWilkes! Would a decorator on the route – (similar to our `@serializable` decorator) which establishes a lock on the table and ensures that the lock is removed regardless of what happens during the route processing – be helpful? Of course if the route itself hangs (e.g. because it encounters a different locked table), then that wouldn't help. However, this is the only place in Dallinger where we're doing any sort of explicit locking, and I wonder if some sort of exception is leaving the lock in place and causing problems.

**Comment by MatthewWilkes** [comment]
I think it'd only be helpful for debugging this, really. Usually postgres is very good at ordering its work to avoid deadlocks, hence why I'm a bit surprised we are having them with only one explicit lock. The advantage to doing another is it'd let you control the locking, so you could see if locking earlier was helpful. It's not exactly science, though. More to try and work out what/where the conflicting lock is.

Most locks we will be encountering are implicit and at row level, this is different specifically because we wanted that serializability across rows in the participants table. Perhaps that was the issue, that we were struggling with retries when we had serializable and so tried to make them queue up more explicitly with this lock?

**Comment by pmcharrison** [comment]
Thanks so much everyone for this discussion, and in particular @MatthewWilkes for this useful long-term memory! Like Matthew mentioned, I did try imposing additional locks on other queries to avoid this problem, in particular row-level locks via `with_for_update`, but curiously I could not avoid the problem using this. It might be that under the hood there are some hidden queries happening (via relationships) that mean that the locks aren't comprehensive enough. I agree with Matthew that these locks aren't elegant though and nice to avoid if possible.

**Pull request merged**
