### PR TITLE
Test fixups

### PR DESCRIPTION
**Pull request by jessesnyder**
## Description
Improvements to existing test infrastructure

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
@jessesnyder What's the logic here? Do we not need the directory to be set? We should also wrap the yield in a try/finally, so the cleanup code happens even if the test fails.

**Comment by jessesnyder** [comment]
@MatthewWilkes The `in_tempdir` fixture creates a temp directory and puts you in it (and returns you to the starting dir afterwards), so the `tempdir` fixture doesn't need to do it also.

I agree some exception handling would be a good addition.

**Comment by jessesnyder** [comment]
@MatthewWilkes The `in_tempdir` fixture creates a temp directory and puts you in it (and returns you to the starting dir afterwards), so the `tempdir` fixture doesn't need to do it also.

I agree some exception handling would be a good addition.

**Comment by jessesnyder** [comment]
@MatthewWilkes I don't know what you mean by a "wider push"?

**Pull request merged**
