### PR TITLE
Allow `extra_parameters` configuration from classmethod

### PR DESCRIPTION
**Pull request by alecpm**
## Description
This PR implements an optional `extra_parameters` `classmethod` on the Experiment class. The method is called automatically during experiment initialization. The method should only be called once for a given `Configuration` instance. Includes documentation and test updates.

## Motivation and Context
See issue #2432

## How Has This Been Tested?
Automated tests have been updated to include class based parameter registration. The Bartlett1932 demo has been updated to use a class method for parameter registration.

### CODE REVIEW

**Comment by pmcharrison** [comment]
Hi @alecpm, thanks very much for this! It fixed the recursion issue. However, it uncovered another integration issue that we are seriously struggling to fix. Here's what I know: 

- This issue is not new to the present merge request, but it was introduced in the original merge request.
- It is due to the following passage in the definition of `register_extra_parameters` : `exp_klass = load()`.
- The error doesn't happen with that particular call, but it happens because of it, sometime after the third time that `register_extra_parameters`, in the process of trying to setup the Heroku services. If you get rid of this line, then the code runs (in particular, `exp_klass()` on the next line isn't responsible for the problem, it's specifically `exp_klass = load()`.
- The error message is unfortunately not informative at all: `[ERROR] Exception in worker process\n']`.

Do you have any tips for debugging these Gunicorn processes? Do you have any idea about what might be going on here? The problem is clearly PsyNet specific but it's a complex job to try and pin down what part of PsyNet is causing this problem.

**Comment by alecpm** [comment]
Strange. Generally what I do in this case is look in the output for the temp directory created for the experiment. You should be able to cd into that directory and run `dallinger_heroku_web` or `dallinger_heroku_worker` if that's the process that's failing. Those will generally give you good tracebacks and point you to the actual cause. You will need to make sure the shell you are using in the tmp directory has the same python you used to run Dallinger, and you'll probably also need to explicitly do "export PORT=5000" before running those commands.

**Comment by pmcharrison** [comment]
That's really helpful, @alecpm - thanks! We'll let you know how we get on.

**Comment by pmcharrison** [comment]
That worked perfectly, @alecpm, thanks! Here's the error we got:

```
File "/home/frank/.virtualenvs/dlgr_env/lib/python3.8/site-packages/flask/app.py", line 1220, in add_url_rule
    raise AssertionError('View function mapping is overwriting an '
AssertionError: View function mapping is overwriting an existing endpoint function: dashboard.timeline
[2021-01-20 13:13:12 +0100] [887117] [INFO] Worker exiting (pid: 887117)
```

If I had to guess, I would say the problem is that the experiment is getting imported twice because of the new changes to extra_parameters, and this is causing an error with the customised dashboard, because the same route is getting registered twice. What do you think, @alecpm ?

**Comment by alecpm** [comment]
Interesting. I ran into this error when working on the `experiment_routes` feature (#2525) and I believe it indicates that a Flask route is being registered twice with the same name. To work around this I created an alternate mechanism for registering routes that defers the actual registration until experiment server startup.

In this case, I'm not sure how it's happening, but my guess is you are registering a this `dashboard.timeline` route in a place that's causing it to be double registered. The issue is probably that the experiment file gets imported from two different locations depending on when the import occurs. Normally a module can be imported multiple times with the side-effects only occurring once, but if the file is being copied around and imported from different locations at different times then the import time code will be run repeatedly.

I'm not sure how we can avoid this sort of thing generally, since load() can generally be called multiple times, resulting in importing the module from different locations. Essentially we will need to try to minimize/discourage reliance on import time side-effects. That's tricky since the Flask route decorators create such side-effects and do so in a way that's explicitly non-idempotent. In this case I wonder if it's a side-effect if calling `config.load()` inside of your experiment `__init__`. I wonder if maybe you should check `config.ready` to determine whether it's an appropriate time to set parameters, but not actually call `config.load()`.

**Review by jessesnyder — APPROVED** [review]
I wish `Configuration.register_extra_parameters()` at least passed the config object to the experiment instead of making the experiment immediately retrieve it, but that's what we do for the old module function, and consistency trumps other concerns.

**Comment by jessesnyder** [comment]
@alecpm It sounds like the problem experienced by @pmcharrison is related to route registration. Is it an indirect consequence of the changes in the PR, or unrelated? If unrelated I'm inclined to move ahead with the merge.

**Comment by alecpm** [comment]
I think it's related to the fact that we're making a new call to `experiment.load()` to import the class from another point in the startup process (when `config.load()` is called). The result is that the import may happen twice, but since `config.load()` is an undocumented API that is not supposed to be used directly at all by experiments, I don't think this is necessarily a blocker.

**Comment by pmcharrison** [comment]
As mentioned in #2525 I'm passing this onto Frank, he will help make sure that everything ends up working properly with PsyNet.

**Comment by jacobyn** [comment]
Here is some of the relevant code from our code base, unfortunately it is written by Peter who is not available.
I am trying to figure out what is the strategy that can be used to bypass the issue.

```
def __init__(self, session=None):
        super(Experiment, self).__init__(session)

        config = get_config()
        if not config.ready:
            config.load()

        self._background_tasks = []

```


and here:
```

def import_local_experiment():
    # Imports experiment.py and returns a dict consisting of
    # 'package' which corresponds to the experiment *package*,
    # 'module' which corresponds to the experiment *module*, and
    # 'class' which corresponds to the experiment *class*.
    # It also adds the experiment directory to sys.path, meaning that any other
    # modules defined there can be imported using ``import``.
    # import pdb; pdb.set_trace()
    config = get_config()
    config.load()
    initialize_experiment_package(os.getcwd())
    dallinger_experiment = sys.modules.get("dallinger_experiment")
    sys.path.append(os.getcwd())
    import dallinger.experiment
    try:
        module = dallinger_experiment.experiment
    except AttributeError as e:
        raise Exception(f"Possible ModuleNotFoundError in your experiment's experiment.py file. " \
                        f"Please check your imports!\nOriginal error was \"AttributeError: {e}\"")

    return {
        "package": dallinger_experiment,
        "module": module,
        "class": dallinger.experiment.load()
    }
```

**Comment by pmcharrison** [comment]
The config loading in `Experiment.__init__` should be fixed by the
staticmethod / classmethod change that @alecpm has made. However the
current problem is now with the dashboard double registration, and we're
not clear yet whether this reflects a PsyNet issue or a Dallinger issue. It
would be useful for Frank to share the code where the custom dashboard
panel (timeline) gets registered, and for @alecpm et al to check whether
this is done correctly.

**Comment by fmhoeger** [comment]
Hello @alecpm ,
this is the code where we extend the dashboard with an additional tab "Timeline":

```
class Experiment(dallinger.experiment.Experiment):
    def __init__(self, session=None):
        super(Experiment, self).__init__(session)

        config = get_config()
        if not config.ready:
            config.load()

        self._background_tasks = []
        self.participant_fail_routines = []
        self.recruitment_criteria = []
        self.base_payment = config.get("base_payment")

        if session:
            if not self.setup_complete:
                self.setup()
            self.load()
            
            …
   
   def load(self):
        …
        tab_title = "Timeline"
        if all(tab_title != tab.title for tab in dashboard_tabs):
            dashboard_tabs.insert_after_route(tab_title, "dashboard.timeline", "dashboard.monitoring")
```
Let me know if you need any more information/code snippets to get this resolved.

**Comment by alecpm** [comment]
In general, I would recommend changing code like:
```
    if not config.ready:
        config.load()
    ....
    self.base_payment = config.get("base_payment")
```
to e.g.:
```
    if config.ready:
        self.base_payment = config.get("base_payment")
```
This issue won't affect many experiments, but I think experiments that call `config.load()` inside of `Experiment.__init__` and also register Flask routes at the module level could cause doubled route registrations, resulting in that error. The new route registration mechanism defined in #2525 would also resolve this issue.

**Comment by alecpm** [comment]
Any calls to `dallinger.experiment.load()` (which is called by `config.load()`) outside of experiment_server/config setup could also result in duplicate route registration. It would be nice if registering a Flask route twice didn't result in these delayed errors, but there's not much we can do about that beyond the alternate registration mechanism proposed in #2525.

**Comment by fmhoeger** [comment]
@alecpm Thanks for your feedback! We currently have calls to `dallinger.experiment.load()` in four places and calls to `config.load()` in three other places in our code. So this would require quite some effort to get rid of and I'm not sure if this is easily possible in the short term.

**Comment by alecpm** [comment]
With this PR `experiment.load()` should generally be safe to call from your experiment code, the problem only occurs when it's called multiple times before the experiment server is setup (which would cause re-registrations of custom experiment routes if defined at the module level).

I think any place that calls `config.load()` will usually be fine with a simple `get_config()`. There may be some special cases where `Experiment.__init__` is called before the config is loaded, and in such cases you would want to check `config.ready` before setting or reading config values within `__init__`. However, I don't think under normal circumstances `Experiment.__init__` would be called before the config was loaded (the original `extra_parameters` implementation did this but it's been refactored to avoid doing that).

Unfortunately, there's no way to be able to use the Experiment class to make config or route changes without making calls to `experiment.load()` before the config is loaded or routes are registered with the flask application. I think this PR and PR #2525 together should be safe to use. I'm in the process of rebasing them so you won't see the impact of the earlier implementation of #2432 when testing.

**Comment by alecpm** [comment]
I don't think the startup error ues related to the dashboard tabs, but to flask routes registered at the module level using `@extra_routes.route(...)` and how that interacts with `experiment.load` being called earlier in the startup process, possibly as a result of `config.load` being called in the experiment init.

**Comment by pmcharrison** [comment]
I fixed the issues with `config.load()`, this wasn't too difficult. We still had issues with duplicate dashboard registration unfortunately, and I tried various things with not much luck. Eventually I settled on the following stupid but effective hack:

``` py
if not hasattr(dashboard, "timeline"):
    dashboard.timeline = True

    @dashboard.route("/timeline")
    ....
```

I did have a look at the Dallinger tests and couldn't see a test for `dashboard.route()`, which made me idly wonder whether this would be a good thing to add, in case new dashboard routes are broken in general.

**Comment by alecpm** [comment]
@pmcharrison So did the route registration check fix your issues even if you kept `config.load()` in place? That's definitely a hack I'd prefer to avoid, but it might be necessary for module level route registrations in experiment.py

Adding a test for custom dashboard routes probably makes sense – similar to the way we test custom experiment routes. I do think putting the dashboard routes and their registration on the class, in analogy to #2525, might also be preferable to using import time registrations, which is the real source of these issues.

**Comment by pmcharrison** [comment]
Yes, it did fix it even with `config.load()`, actually. I removed
`config.load()` just to be safe though.

Thanks for your help!

**Comment by alecpm** [comment]
@pmcharrison That's good to hear. Locally I've got a test for dashboard route registration, and it seems to fail in the same way you were seeing on `master`, so that doesn't seem to be an issue specific to this PR. It appears to be the result of multiple experiment package imports triggered by `experiment.load()` called when using the class to determine the `extra_files`. I think your work around is probably the best we can do unless we provide some mechanism for doing dashboard route registrations in a non-conflicting way on the experiment class as I do for experiment route registrations in #2525.

I'm also finding a number of test isolation issues related to custom route registration, which are a bit tricky to dig into, but I think this branch is safe to merge.

**Comment by alecpm** [comment]
Proposed CHANGELOG entry:

* Added `experiment_parameters` `classmethod` to experiment class to simplify registration of custom `config` variables.

**Pull request merged**
