### PR TITLE
Release9.1.0

### PR DESCRIPTION
**Pull request by jessesnyder**
## Description
Release PR

VS Code unexpectedly reformatted the CHANGELOG markdown, but I'm not sure this isn't a good thing.

### CODE REVIEW

**Review by pmcharrison — COMMENTED** [review]
Thanks @jessesnyder !

We are missing #4293, which is a very important part of the development cycle. I don't think you had a chance to review it but @fmhoeger and I have been playing with it and giving feedback. I think the best thing to do is merge it but maybe mark it as experimental in the docs?

There is also #3799, which adds another experimental new feature. It's actually been waiting for months for user testing but we haven't managed to do it. Do you think you'd be willing to have a quick look over this and perhaps again merge it, but marked as experimental? I think it's useful to get these experimental features out into the main release otherwise I'm worried they'll get stuck in the doldrums forever.

**Comment by jessesnyder** [comment]
I don't want to be a bottleneck here. Let's just merge whatever is safe to merge, but if there are things to document, I don't think I can do that.

@silviot Do you have time to add any necessary caveats to documentation on these PRs?

I think @fmhoeger also wants to get another round of dependency updates in before the release. 

I'd say let's try to get all this taken care of and I'll try again for a release on Monday (I'm not working tomorrow).

**Comment by jessesnyder** [comment]
Dependency updates merged to `master`. I'll start again on a release PR once we get the other work merged.

**Comment by pmcharrison** [comment]
Thanks @jessesnyder and @silviot ! It would be great if you could keep us posted on the timeline. It would be valuable to get a release by end of Wednesday and if necessary maybe this means delaying Silvio's bit

**Comment by jessesnyder** [comment]
We've decided to go ahead with the release without @silviot's last PR merged, so I'll get that done today.

**Comment by pmcharrison** [comment]
Thanks!
________________________________

**Pull request closed without merging**
