### PR TITLE
Fix iterated drawing demo.

### PR DESCRIPTION
**Pull request by cguardia**
The demo had two problems. It used string handling that was not compatible with Python 3, and the javascript import ordering was wrong in the layout template.

It works now both locally and in Heroku.

### CODE REVIEW

**Comment by witekdev** [comment]
Strangely there were many (16) Hits in the dev sandbox for this demo and all were giving a Heroku message:

untitled-2
untitled-3

I had to loop between accept HIT and skip and Return before I eventually found my HIT that I could accept and complete.

**Comment by cguardia** [comment]
@witekdev I think the heroku problem that you had is unrelated to the demo. This happens to me from time to time, for some reason mostly when running a sandbox test after midnight central time.

**Comment by cguardia** [comment]
@jessesnyder the contents method also caught my attention. I think you are right that we should keep it. Maybe we can add a second image?

**Comment by witekdev** [comment]
> @witekdev I think the heroku problem that you had is unrelated to the demo. This happens to me from time to time, for some reason mostly when running a sandbox test after midnight central time.

Interesting, a passing thought I had is that perhaps unexpired HITs from previous testing runs were still left over (with their Heroku app MIA/destroyed), and somehow were interfering with my newer HIT.
I was testing in my early afternoon, so likely early morning hours of central time. Curious if and when this issue shows up again. Out of curiousity @jessesnyder have you seen this phenomenon before?

**Comment by cguardia** [comment]
@witekdev I was referring to the JSON error. The many hits problem has happened to me, but it can mostly be avoided by clicking on the recruitment link that comes out in the experiment console output.

**Comment by witekdev** [comment]
> @witekdev I was referring to the JSON error. The many hits problem has happened to me, but it can mostly be avoided by clicking on the recruitment link that comes out in the experiment console output.

Ah, thats a good tip :muscle: Thanks!

**Comment by jessesnyder** [comment]
(I had intended to approve this after the first look. Dealing with the single/multi image question isn't a requirement for merge, in my opinion.)

**Pull request merged**
