### PR TITLE
Refactoring of `advertisement()`

### PR DESCRIPTION
**Pull request by polvanrijn**
Refactoring of `advertisement()` to prepare the advertisement in a separate function. This allows wrappers around dallinger, e.g. PsyNet, to use other rendering functions than the one used in Flask. This is for example important, if you want to add custom Jinja filters or add translations.

### CODE REVIEW

**Comment by polvanrijn** [comment]
@fmhoeger

**Comment by pmcharrison** [comment]
Thanks @polvanrijn! Can you move the logic from utils.py back into experiment_sever.py? Done correctly, the diff should simplify quite a lot this way.

**Comment by polvanrijn** [comment]
I actually had this before, but this led to a circular import in psynet. We can maybe resolve this in our meeting in an hour?

**Comment by pmcharrison** [comment]
Interesting, I wonder how that could happen!
________________________________

**Review by pmcharrison — APPROVED** [review]

**Review by fmhoeger — APPROVED** [review]

**Comment by fmhoeger** [comment]
@polvanrijn You are ready to (squash and) merge this one.

**Pull request merged**
