### PR TITLE
Remove deprecation warnings and update mentions of Python versions

### PR DESCRIPTION
**Pull request by fmhoeger**
* Remove deprecation warnings caused by utilization of now deprecated `pkg_resources` API
* Drop leftovers of support for Python 3.7 (importlib_metadata)
* Remove all mentions of Python 3.7
* Update all occurrences of Python version to 3.8, 3.9, and 3.10 only

### CODE REVIEW

**Comment by fmhoeger** [comment]
@pmcharrison You might want to have a look.

**Comment by pmcharrison** [comment]
Thanks @fmhoeger! Looks fine as far as I can tell but it will be important to test it. Maybe you could try deploying a test app to Docker SSH and to Heroku in case you haven't already?

**Comment by fmhoeger** [comment]
> Thanks @fmhoeger! Looks fine as far as I can tell but it will be important to test it. Maybe you could try deploying a test app to Docker SSH and to Heroku in case you haven't already?

Successfully tested deployment to Docker SSH and to Heroku after fixing a bug in MR #5215 related to the generation of `docker-compose.yml`.

**Comment by pmcharrison** [comment]
> > Thanks @fmhoeger! Looks fine as far as I can tell but it will be important to test it. Maybe you could try deploying a test app to Docker SSH and to Heroku in case you haven't already?
> 
> @pmcharrison Successfully tested deployment to Docker SSH and to Heroku after fixing a bug in MR #5215 related to the generation of `docker-compose.yml`.

Sorry @fmhoeger, I'm still nervous about this. I think we need to understand why this MR introduced that problem in the first place, i.e. why did the value of `docker volumes` end up changing? This may be due to a deeper problem that we haven't understood yet.

**Comment by fmhoeger** [comment]
> > > Thanks @fmhoeger! Looks fine as far as I can tell but it will be important to test it. Maybe you could try deploying a test app to Docker SSH and to Heroku in case you haven't already?
> > 
> > 
> > @pmcharrison Successfully tested deployment to Docker SSH and to Heroku after fixing a bug in MR #5215 related to the generation of `docker-compose.yml`.
> 
> Sorry @fmhoeger, I'm still nervous about this. I think we need to understand why this MR introduced that problem in the first place, i.e. why did the value of `docker volumes` end up changing? This may be due to a deeper problem that we haven't understood yet.

Does my comment in https://github.com/Dallinger/Dallinger/pull/5215#discussion_r1199685417 explain the issue?

See also this very recent change: https://github.com/Dallinger/Dallinger/commit/eab80d9cffc9598de093d838af111e4573a666f8

**Comment by pmcharrison** [comment]
Oh no, I see I introduced the original bug! That all makes sense then. Sorry that I've been holding up this PR with these debates....

**Pull request merged**
