### PR TITLE
Extend template inheritance (2)

### PR DESCRIPTION
**Pull request by vlall**
This is the same as PR #761, except we want to rebase/merge to master. See #761 for full discussion.

### CODE REVIEW

**Comment by vlall** [comment]
Still getting the **TemplateNotFound, Internal Server Error** despite my attempt to fix with last commit.

**Comment by vlall** [comment]
I see, so I needed move everything to the **base** folder, I couldn't just rename and reference the **default** folder. Now the issue with testing is the disabled Begin button which it looks like there's a reason behind doing that @jessesnyder

**Comment by jessesnyder** [comment]
Updated ad.html and the "begin experiment" button now works (and is disabled on click) correctly using a demo experiment that doesn't override ad.html (I used Bartlett1932). Tests pass for me locally, but seem to be hanging on Travis.

**Comment by jessesnyder** [comment]
If test order were reliable, then I'd say the hanging test is `test_load_with_replay(self, replay_loader, export)`, but I don't think order is reliable.

**Pull request merged**
