### PR TITLE
Caddyfile fix

### PR DESCRIPTION
**Pull request by polvanrijn**
We found out that the Caddyfile can get stuck. To avoid it, we added a grace period of 30 seconds and a Yaspin for diagnosing it get's stuck here.

### CODE REVIEW

**Comment by pmcharrison** [comment]
I think you need to add yaspin as a dependency?

**Comment by pmcharrison** [comment]
I think you will then need to run `update_dependencies.sh`

**Comment by pmcharrison** [comment]
Just remembered this PR, guess we can finalise this soon?

**Comment by fmhoeger** [comment]
@polvanrijn You might want to first merge in the `update_dependencies` branch and then run `update_dependencies.sh`

**Comment by pmcharrison** [comment]
Hi @fmhoeger, this adds 141 commits to the branch which is a bit nasty. Maybe it's better just to do a temporary update_depenencies.sh on this branch?

**Comment by fmhoeger** [comment]
Yes, you would want squash these. 
I suggest to just wait until we merged https://github.com/Dallinger/Dallinger/pull/6013 into `master` and then merge in or rebase on the changes in`master`.

**Comment by pmcharrison** [comment]
Ok sounds good!

**Comment by pmcharrison** [comment]
Thanks for fixing the tests @fmhoeger! Happy for me to go ahead and merge?

**Comment by fmhoeger** [comment]
> Thanks for fixing the tests @fmhoeger! Happy for me to go ahead and merge?

Yes, go ahead!

**Review by pmcharrison — APPROVED** [review]

**Pull request merged**
