### PR TITLE
Remove anaconda instructions from documentation

### PR DESCRIPTION
**Pull request by witekdev**
Remove anaconda docs from main documentation table of contents.

All references to anaconda were moved into anaconda section previously, so this is all that is left to remove anaconda from the docs.

### CODE REVIEW

**Comment by vlall** [comment]
We can also get rid of "docs/source/dallinger_with_anaconda.rst"

**Comment by witekdev** [comment]
Sounds good, I just wasn't sure as to what the policy of deleting .rst files was, as opposed to just un-linking them from the TOC. If we ever need it though, we have it in our git history.

Likewise there are 3 other .rst files that maybe up for consideration for deletion?
```
/home/witek/dev/jazkarta/Dallinger/docs/source/gsoc.rst: WARNING: document isn't included in any toctree
/home/witek/dev/jazkarta/Dallinger/docs/source/learning_to_use_dallinger.rst: WARNING: document isn't included in any toctree
/home/witek/dev/jazkarta/Dallinger/docs/source/required_experiment_files.rst: WARNING: document isn't included in any toctree
```

**Comment by witekdev** [comment]
@jessesnyder "docs/source/dallinger_with_anaconda.rst" has been removed.

**Comment by jessesnyder** [comment]
@witekdev I see your point. There seems to be a pattern of unlinking rather than deleting. I don't feel confident to make a decision on this. @vlall?

**Comment by witekdev** [comment]
@jessesnyder well I think we have source control so we can revert and dig something out of source control if we ever miss it, is my opinion. The GSOC I thought was being kept in case it will be used again, at least that was my assumption. Required experiment files and learning to use dallinger we could potentially scrap and look up via git if ever needed.

**Comment by witekdev** [comment]
Likewise I think we can safely delete (as has been done in this PR) the anaconda install document.

**Pull request merged**
