### PR TITLE
Add a check for circular imports in experiment module loading

### PR DESCRIPTION
**Pull request by pmcharrison**
## Description

Suppose you have a circular import in experiment.py. One way of achieving this is to write something like 

```
from dallinger.experiment_server.experiment_server import app
```

in your experiment.py.

`dallinger.experiment.load()` will fail ("Could not import experiment class"), but with no hints about how to debug.

I have added some extra logic that checks whether the experiment module is only partly initialized, which is a signature of a circular import. This is then reported as an error message. This should be helpful for people debugging their experiments.

## How Has This Been Tested?

I tested this by running `dallinger verify` on an experiment with a circular import. It gave the following message, as desired:

```
(psynet) $ dallinger verify  

❯❯ Verifying current directory as a Dallinger experiment...
✓ config.txt is PRESENT
✓ experiment.py is PRESENT
✓ Size OK at 3MB (max is 50MB)
2022-04-21 12:58:57,715 - /Users/peter/git/dallinger/dallinger/experiment.py - ERROR - Error retrieving experiment class
2022-04-21 12:58:57,715 - /Users/peter/git/dallinger/dallinger/experiment.py - ERROR - The experiment module is only partly initialized. Maybe you have a circular import?
2022-04-21 12:58:57,716 - /Users/peter/git/dallinger/dallinger/experiment.py - ERROR - Could not import experiment.
✓ experiment.py defines 1 experiment
✓ no file conflicts

❯❯ ✓ Everything looks good!
```

This highlights a secondary issue which is that `dallinger verify` returns `Everything looks good!` even if the experiment class can't be imported reliably, which we have found does introduce downstream problems in Dallinger experiments. This appears more complicated to solve and is outside the scope of this pull request.

### CODE REVIEW

**Comment by pmcharrison** [comment]
There are two CI errors but they are already happening on master and are not specific to this PR.

**Comment by jacobyn** [comment]
@pmcharrison is there a way to add to this "Maybe you have a circular import?" the module or location (line number) indicating the circular import? For me just specifying circular import is already super helpful but specifying the module/line is even better.

**Comment by pmcharrison** [comment]
Good question. I don't think so, though -- I think if there was an easy way of identifying that, Python would already include it in their circular imports error message, which unfortunately they don't/

**Review by fmhoeger — APPROVED** [review]
LGTM, except for an automatic test that could be added in the case we really have a circular import.

**Pull request merged**
