### PR TITLE
Non-asciii filename support

### PR DESCRIPTION
**Pull request by jessesnyder**
## Description
Bug fix for #2092 

## How Has This Been Tested?
- [x] Automated tests
- [x] Test repo on Mac OS
- [x] Test repo on Ubuntu

## Demo

```
>>> os.listdir('.')
['.DS_Store', 'foo\nbar', 'ånøthér file.txt', '.git', 'fîlé.txt']
>>> from dallinger.deployment import ExperimentFileSource
>>> src = ExperimentFileSource()
>>> src.files
{'./fîlé.txt', './foo\nbar', './ånøthér file.txt'}
```

### CODE REVIEW

**Comment by pmcharrison** [comment]
Works. Thanks for the quick fix!

**Comment by jessesnyder** [comment]
@MatthewWilkes @pmcharrison has tested against his actual failure context. Can you approve if you see fit?

**Comment by MatthewWilkes** [comment]
Actually, it's not handling newlines right either. Its escaping them, so `foo\nbar` is being read as `foo\\nbar`. Sorry!

**Comment by jessesnyder** [comment]
Newlines are definitely a problem (putting aside whether they're a problem we need to worry about), but I can't reproduce any problem with non-ascii characters. I've added a test for this:
https://github.com/Dallinger/Dallinger/pull/2093/files#diff-87010571bbeeee0b9a13279c493670f3

**Comment by jessesnyder** [comment]
@MatthewWilkes Well that was fun. Still no newlines in filenames, but everything else should work on Ubuntu now I hope(?)

**Comment by jessesnyder** [comment]
@MatthewWilkes During standup we agreed that you should take a final pass at testing this on Ubuntu, since that's where many of the complications arise, and it's hard for anyone else to test on that platform. Hope that's OK!

**Pull request merged**
