### PR TITLE
Fix deprecation warning: Rename method_whitelist to allowed_methods

### PR DESCRIPTION
**Pull request by fmhoeger**
`urllib3.util.retry.Retry` only accepts `allowed_methods` instead of `method_whitelist` as an argument in the future.
 
```
 /home/frank/Dallinger/dallinger/command_line/docker_ssh.py:477: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
  retry_strategy = Retry(
```

### CODE REVIEW

**Review by silviot — APPROVED** [review]
LGTM. It will break when people installing dallinger already have a pinned `urllib3` version prior to 1.26.0 and they don't use the `requirements.txt` pinning, but that should be a very rare case. For these reasons I'm approving the change and providing suggestions to mitigate this rare case if desirable.

The `urllib3` module can be inspected [as suggested here](https://github.com/urllib3/urllib3/issues/2092#issuecomment-733738879) to make sure we use the new method name only if available:

```python
parameter_name = "method_whitelist"
if hasattr(urllib3.util.Retry.DEFAULT, "allowed_methods"):
    parameter_name = "allowed_methods"

retry_strategy = Retry(
    total=30,
    backoff_factor=0.2,
    status_forcelist=[429, 500, 502, 503, 504],
    **{method_name: ["POST"]}
)
```

**Comment by jessesnyder** [comment]
@fmhoeger Any reason this hasn't been merged?

**Comment by jessesnyder** [comment]
I agree with @silviot that the existing version pin scenario seems like a small risk, but I also agree that we should support backwards compatibility when we can. Given that he's already done the legwork of outlining a solution, I think it would be good to add it.

**Comment by fmhoeger** [comment]
@jessesnyder Yes, totally agree. I am busy with other things, though, and I am not sure if I find time to work on the PR until the release.

**Comment by fmhoeger** [comment]
@pmcharrison Ready for review

**Review by pmcharrison — APPROVED** [review]

**Pull request merged**
