### PR TITLE
Remove unneeded demo bootstrap css add notification table to DB dashboard

### PR DESCRIPTION
**Pull request by alecpm**
## Description
This addresses #2954 by removing the outdated Bootstrap CSS from demos. I recommend testing the demos thoroughly to ensure the update from Bootstrap 3.3.1 to 4.5 didn't negatively impact the experiment UI. This PR also adds support for the Notification table in the DB dashboard. There is one demo `function_learning` which still includes its own copy of Bootstrap CSS, I didn't update this one because it also included Bootstrap 3 JS and compatibility issues are much more likely if we either update the CSS and JS or only the CSS.

## Motivation and Context
See #2954 and comments

## How Has This Been Tested?
Verified in debug mode that the Database UI behaved as expected with the default bootstrap and included the Notifications table.

### CODE REVIEW

**Comment by pmcharrison** [comment]
Thanks @alecpm - I tested the MCMCP demo and it looks fine with the changes you made.

**Comment by pmcharrison** [comment]
I'm afraid I'm not familiar with the other demos so my guess is as good as yours for them!

**Comment by alecpm** [comment]
I reviewed the `functional_learning` JS and it didn't seem to use any bootstrap 3 specifics. So I've removed the custom bootstrap from there as well. I'll also be removing the bootstrap from the cookie cutter template.

**Review by pmcharrison — COMMENTED** [review]
Thanks @alecpm! Looking good but the notification side doesn't seem quite there yet.

The route works: http://localhost:5000/dashboard/database?model_type=Notification

Screenshot 2021-07-13 at 09 44 58

but the `Notification` table doesn't appear in the dropdown: 

Screenshot 2021-07-13 at 09 51 19

**Comment by pmcharrison** [comment]
(I was testing the MCMCP demo)

**Comment by alecpm** [comment]
@pmcharrison Weird, when I run on this branch using MCMCP I see the following:

Screen Shot 2021-07-13 at 12 59 30 AM

Is it possible you were running the updated demo experiment, but with an older (pip installed?) Dallinger release?

**Comment by pmcharrison** [comment]
Oh dear, you're right. Sorry about that! I normally have it installed as editable, but apparently not this time!

**Review by pmcharrison — APPROVED** [review]

**Pull request merged**
