### PR TITLE
Use "dallinger" S3 bucket for all backups

### LINKED ISSUE #421: Can't hibernate experiment
After running dallinger hibernate --app [appID], I get the following error and am unable to hibernate my experiment: 

<Error><Code>TooManyBuckets</Code><Message>You have attempted to create more buckets than allowed</Message><CurrentNumberOfBuckets>101</CurrentNumberOfBuckets><AllowedNumberOfBuckets>101</AllowedNumberOfBuckets><RequestId>D555B1F7B196CF38</RequestId><HostId>r5O+URiHMcMXTrqFbksxECDbe59sx17V//vGF5qbX+HacD24vDJmj9n29+RR+sSTPBa4oTRaIWc=</HostId></Error>

### PR DESCRIPTION
**Pull request by suchow**
Closes #421.

### CODE REVIEW

**Comment by jhamrick** [comment]
Haven't tested it, but looks reasonable to me!

**Comment by suchow** [comment]
Just realized that this won't work as written — S3 bucket names must be globally unique. Thinking through some alternatives now.

**Comment by suchow** [comment]
Okay, this uses an S3 bucket name of `dallinger-x`, where `x` is the first 8 characters of the SHA256 hex digest of the AWS user's canonical ID. Each AWS account thus has its own (probably) unique S3 bucket.

**Comment by suchow** [comment]
Moving this over to the `data` branch.

**Pull request closed without merging**
