### PR TITLE
convert property1 from String to Text

### PR DESCRIPTION
**Pull request by thomasmorgan**
## Description
Converts property1 from String to Text

## Motivation and Context
Allows storage or strings of arbitrary length, which is useful if we want to store complex json objects

## How Has This Been Tested?
I have saved long strings

### CODE REVIEW

**Comment by suchow** [comment]
Is there a reason why we would want `property1` to differ from the other properties?

**Comment by suchow** [comment]
i.e., should we change all the others, too?

**Comment by thomasmorgan** [comment]
we can change the others too, though I thought if this works well we can just delete the others

**Comment by suchow** [comment]
How does this relate to #238 then?

How about we change them all to text for now and then deal with the 1 vs. multiple property columns issue separately?

**Comment by thomasmorgan** [comment]
This relates to #238 because stringified json objects can be long, longer than the 256 chars permitted the the columns previously. At first I thought we would just increase the number of chars permitted, e.g. String(10000), but apparently Text is for strings that could be very long.

OK, I'll set to all to text and we can delete the extra properties later.

**Pull request merged**
