### PR TITLE
Extend template inheritance

### PR DESCRIPTION
**Pull request by MatthewWilkes**
## Description
This adds the ad.html and consent.html templates to the inheritance chain. Users are still required to provide them, but there is a simple version they can inherit from for default functionality.

## Motivation and Context
This makes it easier to develop extensions. Tickets #740 and #735 are related.

## How Has This Been Tested?
Manual test of bartlett only.

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
@suchow I think we can ignore codecov here, the reason the coverage has been reduced is that the code was simplified slightly so there were fewer covered lines than there were before.

**Comment by MatthewWilkes** [comment]
Does anyone know how to make appveyor rebuild here?

**Comment by alecpm** [comment]
I think this PR needs a rebase. It's hard to review in its current state with 173 changed files seemingly unrelated to the story. @MatthewWilkes could you pare this down a bit?

**Comment by vlall** [comment]
I see what @alecpm means.

@MatthewWilkes, is this because the consent pages on those demos are different in a way we might've missed?

**Comment by vlall** [comment]
TemplateNotFound, Internal Server Error when I run this on `master` (PR for a merge to master in #809)

**Comment by vlall** [comment]
Moved to #809

**Pull request closed without merging**
