### PR TITLE
Allow selective disabling of built-in Dallinger Flask routes

### PR DESCRIPTION
**Pull request by jessesnyder**
## Description
Allow experiment authors/deployers to disabled some or all of Dallinger's native routes via the
config.txt machinery.

## Motivation and Context
Addresses #4277 

## How Has This Been Tested?
- `dallinger develop debug`
- automated tests

## CHANGELOG entry
- Feature: A new ``protected_routes`` configuration parameter, coupled with an Experiment property of the same name for disabling Dallinger Flask routes unless authenticated

### CODE REVIEW

**Comment by pmcharrison** [comment]
Hi @jessesnyder, worked well, nice and simple. I proposed a little change where the loading of disabled routes happens in the experiment class, which provides a further avenue to customisation in addition to config.txt. Does that work for you?

**Comment by jessesnyder** [comment]
@silviot I forget how we resolve the fact that Docker tests fail when a new config variable is introduced: https://github.com/Dallinger/Dallinger/runs/8025717241?check_suite_focus=true#step:17:3770

**Comment by pmcharrison** [comment]
The fact that config checks for valid variable names has caused me a lot of pain in the past. It results in these back-compatibility issues such as what you are observing with Docker. It also means that you can't load the config without importing the Experiment class, because the Experiment class is allowed to register additional variable names...

**Comment by pmcharrison** [comment]
@jessesnyder I thought of something else that I should have realised earlier. Disabling routes like this could break dashboard functionality, since the dashboard uses these routes to get summary information. Can I suggest that we modify the behaviour such that, if we disable a route, that route is still accessible if the user is authenticated to the dashboard? I think this is quite possible without changing the currrent approach too much. We currently ensure authentication using the `login_required` decorator, which is passed to every route. However, we want to inject this code in `before_request`. I looked at the documentation for `login_required` and you can instead write something like this:

```py
from flask_login.utils import current_user
if not current_user.is_authenticated:
...
```

So hopefully it's just a one-liner?

In this case, maybe we should renamed `disabled_routes` to `protected_routes`?

**Comment by jessesnyder** [comment]
@pmcharrison Took your suggestion about checking authentication, and dealt with a cascade of test problems which came as a side effect of these changes. Hopefully this gets us close. I'm done for the week, but will check in on Monday.

**Comment by jessesnyder** [comment]
Moved this PR out of draft state.

**Comment by jessesnyder** [comment]
> The fact that config checks for valid variable names has caused me a lot of pain in the past. It results in these back-compatibility issues such as what you are observing with Docker. It also means that you can't load the config without importing the Experiment class, because the Experiment class is allowed to register additional variable names...

I wouldn't object to revisiting the rationale for performing this validation. :)

**Review by silviot — APPROVED** [review]

**Review by pmcharrison — APPROVED** [review]

**Pull request merged**
