### PR TITLE
Release version 3.0.0

### PR DESCRIPTION
**Pull request by suchow**
Release version 3.0.0. This is a work in progress — I believe we are feature complete for a 3.0.0 release, but this needs a considerable amount of manual testing given how much of the codebase isn't hit by the test suite. Along the way, I'll see if any of this testing can be automated.

Demos (test locally)
- [x] 2048
- [x] Bartlett (1932), stories
- [x] Networked chatroom-based coordination game
- [x] Concentration
- [x] Transmitting functions
- [x] Bartlett (1932), drawings
- [x] Markov Chain Monte Carlo with People
- [x] Rogers’ Paradox
- [x] The Sheep Market
- [x] Snake
- [x] Vox Populi (Wisdom of the crowd)

CLI
- [x] `help`
- [x] `awaken`    Restore the database from a given url.
- [x] `debug`     Run the experiment locally.
- [x] `deploy`    Deploy app using Heroku to MTurk.
- [x] `destroy`   Tear down an experiment server.
- [x] `export`    Export the data.
- [x] `hibernate` Pause an experiment and remove costly...
- [x] `logs`      Show the logs.
- [x] `qualify`   Assign a qualification to a worker.
- [x] `sandbox`   Deploy app using Heroku to the MTurk Sandbox.
- [x] `setup`     Walk the user though the Dallinger setup.
- [x] `summary`   Print a summary of a deployed app's status.
- [x] `verify`    Verify that app is compatible with Dallinger.

Integration test
- [x] Run Bartlett (1932) in sandbox
- [x] Run Bartlett (1932) live

Python module
- [x] Run Bartlett (1932) in sandbox via `experiment.run()`

**UPDATE** I've now finished testing all the above functionality, making bug fixes along the way.

### CODE REVIEW

**Comment by suchow** [comment]
@thomasmorgan I've gotten Rogers pretty close to running on 3.x. I believe the only thing left is updating the status checking to use the new string-based statuses instead of the numeric statuses. I'm a bit hazy on that right now. Could you take a look and take a stab at updating this branch accordingly?

**Comment by suchow** [comment]
@thomasmorgan (Alternatively, maybe we should remove the demo until the paper is published?)

**Comment by thomasmorgan** [comment]
@suchow I think I've got Rogers working (though haven't really tested it!). There were only a couple of uses of Participant.status so that was easy. That aside I updated a bunch of the methods to be easier to read.

Sorry about the period irritating the bot. Isn't it counterintuitive to have commit names start with a capital, but not end with a period?

**Comment by suchow** [comment]
@thomasmorgan Thanks!

Regarding commit messages, it may be counterintuitive, but at least it's a standard: https://chris.beams.io/posts/git-commit/.

**Pull request merged**
