### PR TITLE
Stories/484 standardize demos

### PR DESCRIPTION
**Pull request by jessesnyder**
## Description
Standardize included demos and bring them up to date with current best practices.

## Motivation and Context
The included demos should serve as solid examples for people developing new custom experiments. Additionally, they should be as concise as possible to reduce their maintenance burden.

## Summary of Changes
- Fix automated tests in `test_demos.py` and make the demos more testable
- Be consistent about accessing config at runtime, and reading values into experiment properties in `Experiment.configure()`
- Demonstrate custom config variables in Bartlett
- Make Bartlett shorter (3 participants) by default
- Only go to the questionnaire when `createAgent()` returns a 403 status, otherwise error
- Standardize instructions layout to use an /instructions directory, with instruct-ready.html as the final (and possibly only) instructions page
- Use {% block libs %} for including JS files, and {% block scripts %} for `<script />` tags
- Remove unused templates
- Standardize on "experiment.html" for main experiment template
- Make more consistent and aggressive use of template inheritance to reduce maintenance
- Remove inclusions of JS files already included by Dallinger (store+json2.min.js in particular)
- Standardize imports of `dallinger.x` packages to fully import target package (`from dallinger.models import Network` as opposed to `import dallinger`, then `dallinger.models.Network` in use)
- Rogers demo received comprehensive updates and simplifications
- use `redis_size = hobby-dev` in all demos

## Related
PR on cookiecutter-dallinger: https://github.com/Dallinger/cookiecutter-dallinger/pull/9

## How Has This Been Tested?
- Improved automated demo tests (still very superficial)
- All demos were tested repeated in debug mode

## Review
-- @MatthewWilkes Reviewed the new cleanup of `sys.modules` in `verify_experiment_module()`

### CODE REVIEW

**Comment by vlall** [comment]
This is a big one.. maybe some extra reviewers would be helpful. We should also try each demo and see if they still work as intended.

**Comment by witekdev** [comment]
We use Redis Premium 0 setting and despite telling users about the hobby-dev tier here 
http://docs.dallinger.io/en/latest/demos_on_heroku.html we still have the demos use the premium 0 option which is not free. 

https://elements.heroku.com/addons/heroku-redis/

The differences are:
**Hobby-dev:**
```
Memory 25 MB
Connection Limit 20
Performance Analytics
Metric Logs
```

**Premium 0**
```
Memory 50 MB
Connection Limit 40
High Availability
Persistence
Performance Analytics
Metric Logs
```

Do we need _High Availability_ & _Persistence_ for the demos?
If not, perhaps we should add ``` redis_size = hobby-dev ``` into all the demos config.txt in this PR?

**Comment by alecpm** [comment]
I agree with @witekdev, we should default to hobby-dev Redis for the demos.

**Comment by witekdev** [comment]
Just a reminder to merge https://github.com/Dallinger/cookiecutter-dallinger/pull/9 when we merge this PR for consistency

**Comment by jessesnyder** [comment]
Man I wish we had our defaults in the base config (global_config_defaults.txt I guess) instead of scattered around the code, but that's another story.

Update to use `redis_size = hobby-dev` complete.

**Comment by vlall** [comment]
> Man I wish we had our defaults in the base config (global_config_defaults.txt I guess) instead of scattered around the code, but that's another story.
> 
I like this idea, perhaps this should also be a story...

**Pull request merged**
