### PR TITLE
Add language configuration parameter

### PR DESCRIPTION
**Pull request by alecpm**
## Description
Adds a new `language` configuration parameter for setting a gettext language. Default value is `en`.

## Motivation and Context
See #2963

### CODE REVIEW

**Review by jessesnyder — APPROVED** [review]
LGTM

**Comment by alecpm** [comment]
@jessesnyder @silviot any idea why the docker test is failing here? It's not failing on my other PR, so maybe it's sensitive to new configuration parameters somehow?

**Comment by jessesnyder** [comment]
@alecpm I did find this in the logs for the docker run, but I don't understand why it would happen. It's as if it's using the new global_config_defaults but the old config.py. (Maybe you saw this already.)
```

❯❯ Some services did not start properly:

❯❯ bartlett1932_web_1: exited - healthy

❯❯ Traceback (most recent call last):
  File "/usr/local/bin/dallinger_heroku_web", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger_heroku_web')()
  File "/dallinger/dallinger_scripts/web.py", line 11, in main
    launch()
  File "/dallinger/dallinger/experiment_server/gunicorn.py", line 90, in launch
    config.load()
  File "/dallinger/dallinger/config.py", line 274, in load
    self.load_from_file(localConfig)
  File "/dallinger/dallinger/config.py", line 236, in load_from_file
    self.extend(data, cast_types=True, strict=True)
  File "/dallinger/dallinger/config.py", line 131, in extend
    raise KeyError("{} is not a valid configuration key".format(key))
KeyError: 'language is not a valid configuration key'
```

**Comment by silviot** [comment]
@alecpm The docker CI job uses the `bartlett1932` experiment, which specifies its dependencies in `constraints.txt`.
An older dallinger version was specified there, so it was not working.
I updated the dependencies and pushed. Hopefully it will pass this time.
I'm thinking we probably want to not pin dallinger in `bartlett1932` to prevent this problem in the future.

**Comment by alecpm** [comment]
Proposed CHANGELOG entry:

- **FEATURE** Added `language` config parameter to allow configuring a gettext language codes for experiments which may need to do so.

**Pull request merged**
